version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "Abhängigkeit"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "Workflow"
